apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: cilium
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: cilium
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: cilium
  tags:
    karpenter.sh/discovery: cilium
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        # keep these matching your EC2NodeClass
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium","t3.small"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      startupTaints:
        - key: node.cilium.io/agent-not-ready
          value: "true"
          effect: NoSchedule
  limits:
    cpu: 5000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s