apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${issuer_name}
  namespace: cert-manager
spec:
  acme:
    server: ${acme_server}
    email: ${email}
    privateKeySecretRef:
      name: ${issuer_name}
    solvers:
      - http01:
          ingress:
            ingressClassName: ${ingress_class}
